org: tvqqq
app: xemphim-nestjs
service: xemphim-nestjs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  api:
    handler: dist/serverless.handler
    events:
      - httpApi: "*"
